/*
	SQL query templates.
*/



// ======[ TABLE CREATE ]======

char mysql_stagetimes_create[] = 
"CREATE TABLE IF NOT EXISTS `stagetimes` "...
	"(`id` INT NOT NULL AUTO_INCREMENT, "...
	"`auth` INT, "...
	"`map` VARCHAR(128), "...
	"`time` FLOAT, "...
	"`style` TINYINT, "...
	"`stage` INT, "...
	"`postspeed` FLOAT, "...
	"`date` INT, "...
	"`completions` INT, "...
	"PRIMARY KEY (`id`)) "...
	"ENGINE=INNODB;";

char sqlite_stagetimes_create[] = 
"CREATE TABLE IF NOT EXISTS `stagetimes` "...
	"(`id` INT NOT NULL AUTO_INCREMENT, "...
	"`auth` INT, "...
	"`map` VARCHAR(128), "...
	"`time` FLOAT, "...
	"`style` TINYINT, "...
	"`stage` INT, "...
	"`postspeed` FLOAT, "...
	"`date` INT, "...
	"`completions` INT, "...
	"PRIMARY KEY (`id`));";



char mysql_cptimes_create[] = 
"CREATE TABLE IF NOT EXISTS `cptimes` "...
	"(`id` INT NOT NULL AUTO_INCREMENT, "...
	"`auth` INT, "...
	"`map` VARCHAR(128), "...
	"`time` FLOAT, "...
	"`marktime` FLOAT, "...
	"`style` TINYINT, "...
	"`cp` INT, "...
	"`attemps` INT, "...
	"`prespeed` FLOAT, "...
	"`postspeed` FLOAT, "...
	"`date` INT, "...
	"PRIMARY KEY (`id`)) "...
	"ENGINE=INNODB;";

char sqlite_cptimes_create[] = 
"CREATE TABLE IF NOT EXISTS `cptimes` "...
	"(`id` INT NOT NULL AUTO_INCREMENT, "...
	"`auth` INT, "...
	"`map` VARCHAR(128), "...
	"`time` FLOAT, "...
	"`marktime` FLOAT, "...
	"`style` TINYINT, "...
	"`cp` INT, "...
	"`attemps` INT, "...
	"`prespeed` FLOAT, "...
	"`postspeed` FLOAT, "...
	"`date` INT, "...
	"PRIMARY KEY (`id`));";


// view
char mysql_stagewrs_min_create[] = 
"CREATE OR REPLACE VIEW `stagewrs_min` "...
	"AS SELECT MIN(time) time, map, stage, style "...
	"FROM `stagetimes` "...
	"GROUP BY map, stage, style;";

char sqlite_stagewrs_min_create[] = 
"CREATE VIEW IF NOT EXISTS `stagewrs_min` "...
	"AS SELECT MIN(time) time, map, stage, style "...
	"FROM `stagetimes` "...
	"GROUP BY map, stage, style;";


char mysql_stagewrs_create[] = 
"CREATE OR REPLACE VIEW `stagewrs` "...
	"AS SELECT a.* "...
	"FROM `stagetimes` a "...
	"JOIN `stagewrs_min` b "...
	"ON a.time = b.time "...
	"AND a.map = b.map "...
	"AND a.stage = b.stage "...
	"AND a.style = b.style;";

char sqlite_stagewrs_create[] = 
"CREATE VIEW IF NOT EXISTS `stagewrs` "...
	"AS SELECT a.* "...
	"FROM `stagetimes` a "...
	"JOIN `stagewrs_min` b "...
	"ON a.time = b.time "...
	"AND a.map = b.map "...
	"AND a.stage = b.stage "...
	"AND a.style = b.style;";


char mysql_cpwrs_create[] = 
"CREATE OR REPLACE VIEW `cpwrs` "...
	"AS SELECT p.* "...
	"FROM `cptimes` p "...
	"JOIN `wrs` u "...
	"ON p.map = u.map AND p.auth = u.auth "...
	"WHERE u.track = 0;";

char sqlite_cpwrs_create[] = 
"CREATE VIEW IF NOT EXISTS `cpwrs` "...
	"AS SELECT p.* "...
	"FROM `cptimes` p "...
	"JOIN `wrs` u "...
	"ON p.map = u.map AND p.auth = u.auth "...
	"WHERE u.track = 0;";



// ======[ TABLE QUERY ]======

char sql_update_stage_leaderboards[] = 
"SELECT p1.style, p1.stage, p1.auth, p1.date, p1.completions, p1.time, p1.postspeed, p2.name "...
	"FROM `stagetimes` p1 "...
	"JOIN `users` p2 "...
	"ON p1.auth = p2.auth "...
	"WHERE map = '%s' "...
	"ORDER BY p1.time ASC;";

char sql_reload_stage_info[] = 
"SELECT style, stage, date, completions, time, postspeed "...
	"FROM `stagetimes` "...
	"WHERE auth = %d AND map = '%s';";

char sql_reload_checkpoint_info[] = 
"SELECT style, cp, attemps, date, time, marktime, prespeed, postspeed "...
	"FROM `cptimes` "...
	"WHERE auth = %d AND map = '%s';";

char sql_reload_wr_checkpoints[] = 
"SELECT style, cp, attemps, time, marktime, prespeed, postspeed "...
	"FROM `cpwrs` "...
	"WHERE map = '%s';";

char sql_reload_wr_stages[] = 
"SELECT p1.style, p1.stage, p1.auth, p1.time, p1.postspeed, p2.name "...
	"FROM `stagewrs` p1 " ...
	"JOIN `users` p2 " ...
	"ON p1.auth = p2.auth " ...
	"WHERE map = '%s';";

char sql_get_cpr_info[] = 
"SELECT p1.time, p1.cp, p1.postspeed, p1.auth, p2.name "...
	"FROM `cptimes` p1 "...
	"JOIN `users` p2 "...
	"ON p1.auth = p2.auth "...
	"WHERE map = '%s' AND style = 0 AND p1.auth = %d "...
	"ORDER BY p1.cp ASC;";

char sql_get_maptop_info[] = 
"SELECT p1.auth, p1.time, p1.completions, p2.name "...
	"FROM `stagetimes` p1 "...
	"JOIN `users` p2 "...
	"ON p1.auth = p2.auth "...
	"WHERE stage = %d AND style = %d AND map = '%s' "...
	"ORDER BY p1.time ASC "...
	"LIMIT 100;";


// ======[ TABLE UPDATE ]======

char sql_delete_data_checkpoint[] = 
"DELETE FROM `cptimes` "...
	"WHERE auth = %d "...
	"AND map = '%s' "...
	"AND style = %d;";

char sql_delete_data_stage[] = 
"DELETE FROM `stagetimes` "...
	"WHERE stage = %d "...
	"AND style = %d "...
	"AND map = '%s' "...
	"AND auth = %d;";

char sql_insert_data_checkpoint[] = 
"INSERT INTO `cptimes` "...
	"(auth, map, time, marktime, style, cp, attemps, prespeed, postspeed, date) VALUES "...
	"(%d, '%s', %f, %f, %d, %d, %d, %f, %f, %d);";

char sql_update_data_checkpoint[] = 
"UPDATE `cptimes` "...
	"SET attemps = %d, "...
	"time = %f, "...
	"marktime = %f, "...
	"style = %d, "...
	"prespeed = %f, "...
	"postspeed = %f, "...
	"date = %d "...
	"WHERE auth = %d "...
	"AND cp = %d "...
	"AND map = '%s';";

char sql_insert_data_stage[] = 
"INSERT INTO `stagetimes` "...
	"(auth, map, time, style, stage, postspeed, date, completions) VALUES "...
	"(%d, '%s', %f, %d, %d, %f, %d, 1);";

char sql_update_data_stage[] = 
"UPDATE `stagetimes` "...
	"SET time = %f, "...
	"date = %d, "...
	"postspeed = %f, "...
	"completions = completions + 1 "...
	"WHERE stage = %d "...
	"AND style = %d "...
	"AND map = '%s' "...
	"AND auth = %d;";

char sql_update_completion_stage[] = 
"UPDATE `stagetimes` "...
	"SET completions = completions + 1 "...
	"WHERE stage = %d "...
	"AND style = %d "...
	"AND map = '%s' "...
	"AND auth = %d;";