/*
	SQL query templates.
*/



// ======[ FUNCTIONS ]======

char mysql_function_GetWeightedPoints_create[] = 
"CREATE FUNCTION GetWeightedPoints(steamid INT) " ...
	"RETURNS FLOAT " ...
	"READS SQL DATA " ...
	"BEGIN " ...
	"DECLARE p FLOAT; " ...
	"DECLARE total FLOAT DEFAULT 0.0; " ...
	"DECLARE mult FLOAT DEFAULT 1.0; " ...
	"DECLARE done INT DEFAULT 0; " ...
	"DECLARE cur CURSOR FOR SELECT points FROM `playertimes` WHERE auth = steamid AND points > 0.0 ORDER BY points DESC %s; " ...
	"DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1; " ...
	"OPEN cur; " ...
	"iter: LOOP " ...
		"FETCH cur INTO p; " ...
		"IF done THEN " ...
			"LEAVE iter; " ...
		"END IF; " ...
		"SET total = total + (p * mult); " ...
		"SET mult = mult * %f; " ...
	"END LOOP; " ...
	"CLOSE cur; " ...
	"RETURN total; " ...
	"END;;";



// ======[ TABLES CREATE ]======

char mysql_maptiers_create[] = 
"CREATE TABLE IF NOT EXISTS `maptiers` "...
	"("...
		"`map` VARCHAR(128), "...
		"`tier` INT NOT NULL DEFAULT %d, "...
		"`limitPrespeed` TINYINT(1) NOT NULL DEFAULT 1, "...
		"`maxvelocity` FLOAT NOT NULL DEFAULT %f, "...
		"`allowbhop` INT NOT NULL DEFAULT 0, "...
		"PRIMARY KEY (`map`)"...
	") "...
	"ENGINE=INNODB;";



// ======[ TABLES ALTER ]======

char mysql_modify_default_maxvel[] = 
"ALTER TABLE `maptiers` MODIFY COLUMN "...
	"maxvelocity FLOAT NOT NULL DEFAULT %f;";



// ======[ TABLES QUERY ]======

char mysql_GetMapSettings[] = 
"SELECT tier, limitPrespeed, maxvelocity, allowbhop "...
	"FROM `maptiers` "...
	"WHERE map = '%s';";

char mysql_GetMapTier[] = 
"SELECT map, tier "...
	"FROM `maptiers`;";

char mysql_UpdatePlayerRank[] = 
"SELECT u2.points, COUNT(*) "...
	"FROM `users` u1 "...
	"JOIN (SELECT points FROM `users` WHERE auth = %d) u2 "...
	"WHERE u1.points >= u2.points;";

char mysql_UpdateRankedPlayers[] = 
"SELECT COUNT(*) count "...
	"FROM `users` "...
	"WHERE points > 0.0;";

char mysql_UpdateTop100[] = 
"SELECT auth, name, FORMAT(points, 2) "...
	"FROM `users` "...
	"WHERE points > 0.0 "...
	"ORDER BY points DESC "...
	"LIMIT 100;";

char mysql_enable_slow_MVP_system_UpdateWRs[] = 
"      SELECT *, 0 as track, 0 as type FROM `wrhrankmain`  WHERE auth = %d "...
"UNION SELECT *, 1 as track, 0 as type FROM `wrhrankbonus` WHERE auth = %d "...
"UNION SELECT *, -1,         1 as type FROM `wrhrankall`   WHERE auth = %d "...
"UNION SELECT *, -1,         2 as type FROM `wrhrankcvar`  WHERE auth = %d;";

char mysql_disable_slow_MVP_system_UpdateWRs[] = 
"SELECT 0 as wrrank, "...
	"-1 as style, "...
	"auth, "...
	"COUNT(*), "...
	"-1 as track, "...
	"2 as type "...
	"FROM `wrs` "...
	"WHERE auth = %d "...
	"%s %s;";

char mysql_enable_slow_MVP_system_RefreshWRHolders[] = 
"      SELECT 0 as type, 0 as track, style, COUNT(DISTINCT auth) FROM `wrhrankmain` GROUP BY STYLE "...
"UNION SELECT 0 as type, 1 as track, style, COUNT(DISTINCT auth) FROM `wrhrankbonus` GROUP BY STYLE "...
"UNION SELECT 1 as type, -1 as track, -1 as style, COUNT(DISTINCT auth) FROM `wrhrankall` "...
"UNION SELECT 2 as type, -1 as track, -1 as style, COUNT(DISTINCT auth) FROM `wrhrankcvar`;";

char mysql_disable_slow_MVP_system_RefreshWRHolders[] = 
"SELECT 2 as type, "...
	"-1 as track, "...
	"-1 as style, "...
	"COUNT(DISTINCT auth) "...
	"FROM `wrs` "...
	"%s %s %s %s;";


// ======[ TABLES UPDATE ]======

char mysql_SetMapTier[] = 
"REPLACE INTO `maptiers` "...
	"(map, tier) VALUES "...
	"('%s', %d);";

char mysql_SaveMapSettings[] = 
"UPDATE `maptiers` SET "...
		"tier = %d, "...
		"limitPrespeed = %d, "...
		"maxvelocity = %f, "...
		"allowbhop = %d "...
	"WHERE map = '%s';";

char mysql_DeleteMapAllSettings[] = 
"DELETE FROM `maptiers` "...
	"WHERE map = '%s';";

char mysql_disable_weighing_multiplier[] = 
"UPDATE `users` AS U "...
	"INNER JOIN "...
		"(SELECT auth, SUM(points) as total "...
		"FROM `playertimes` "...
		"GROUP BY auth) P "...
	"ON U.auth = P.auth "...
	"SET U.points = P.total "...
	"%s %s;";

char mysql_enable_weighing_multiplier[] = 
"UPDATE `users` SET "...
	"points = GetWeightedPoints(auth) "...
	"WHERE %s %s auth "...
	"IN "...
		"(SELECT DISTINCT auth FROM `playertimes`);";

char mysql_FormatRecalculate_unranked[] = 
"UPDATE `playertimes` SET "...
	"points = 0 "...
	"WHERE style = %d AND track %c 0 %s%s%s;";

char mysql_FormatRecalculate_currentmap_track_main_wr_cached[] = 
"UPDATE `playertimes` PT " ...
	"SET PT.points = ( "...
	"  ((%f * %d) * 1.5) + (%f / 15.0)) " ...
	"* (%f / PT.time) " ...
	"* %f " ...
	"WHERE PT.style = %d AND PT.track = 0 AND PT.map = '%s';";

char mysql_FormatRecalculate_currentmap_track_main_wr_not_cached[] = 
"UPDATE `playertimes` PT " ...
	"INNER JOIN `wrs` WR ON " ...
	"   PT.track = WR.track AND PT.style = WR.style AND PT.map = WR.map " ...
	"SET PT.points = ( "...
	"   ((%f * %d) * 1.5) + (WR.time / 15.0)) " ...
	" * (WR.time / PT.time) " ...
	" * %f " ...
	"WHERE PT.style = %d AND PT.track = 0 AND PT.map = '%s';";

char mysql_FormatRecalculate_currentmap_track_bonus[] = 
"UPDATE `playertimes` PT " ...
	"INNER JOIN `wrs` WR ON " ...
	"   PT.track = WR.track AND PT.style = WR.style AND PT.map = WR.map " ...
	"SET PT.points = ( "...
	"   ((%f * 1) * 1.5) + (WR.time / 15.0)) " ...
	" * (WR.time / PT.time) " ...
	" * %f " ...
	" * 0.25 " ...
	"WHERE PT.style = %d AND PT.track > 0 AND PT.map = '%s';";

char mysql_FormatRecalculate_othermap[] = 
"UPDATE `playertimes` PT " ...
	"INNER JOIN `wrs` WR ON " ...
	"  PT.track = WR.track AND PT.style = WR.style AND PT.map = WR.map " ...
	"INNER JOIN maptiers MT ON " ...
	"  PT.map = MT.map " ...
	"SET PT.points = ( "...
	"  ((%f * MT.tier) * 1.5) + (WR.time / 15.0)) " ...
	"* (WR.time / PT.time) " ...
	"* %f %s " ...
	"WHERE PT.style = %d AND PT.track %c 0;";