/*
	Table querys.
*/



// ======[ TABLE CREATE ]======

char mysql_table_create[] = 
"CREATE TABLE IF NOT EXISTS `styleplaytime` "...
	"(`auth` INT NOT NULL, "...
	"`style` INT NOT NULL, "...
	"`playtime` FLOAT NOT NULL, "...
	"PRIMARY KEY (`auth`, `style`));";



// ======[ TABLE QUERY ]======

char mysql_query_style_playtime[] = 
"SELECT style, playtime "...
	"FROM `styleplaytime` "...
	"WHERE auth = %d;";

char mysql_update_regular_playtime[] = 
"UPDATE `users` "...
	"SET playtime = playtime + %f "...
	"WHERE auth = %d;";

char mysql_update_style_playtime[] = 
"UPDATE `styleplaytime` "...
	"SET playtime = playtime + %f "...
	"WHERE auth = %d AND style = %d;";

char mysql_insert_style_playtime[] = 
"INSERT INTO `styleplaytime` "...
	"(`auth`, `style`, `playtime`) VALUES "...
	"(%d, %d, %f);";

char mysql_show_mapsdone[] = 
"SELECT a.map, a.time, a.jumps, a.id, COUNT(b.map) + 1 as 'rank', a.points "...
	"FROM `playertimes` a "...
	"LEFT JOIN `playertimes` b "...
	"ON a.time > b.time AND a.map = b.map AND a.style = b.style AND a.track = b.track "...
	"WHERE a.auth = %d AND a.style = %d AND a.track = %d "...
	"GROUP BY a.map, a.time, a.jumps, a.id, a.points "...
	"ORDER BY a.%s;";

char mysql_show_mapsleft_have_rankings[] = 
"SELECT DISTINCT m.map, "...
	"t.tier "...
	"FROM `mapzones` m "...
	"LEFT JOIN `maptiers t "...
	"ON m.map = t.map "...
	"WHERE m.type = 0 AND m.track = %d AND m.map "...
	"NOT IN "...
		"(SELECT DISTINCT map "...
		"FROM `playertimes` "...
		"WHERE auth = %d AND style = %d AND track = %d) "...
		"ORDER BY m.map;";

char mysql_show_mapsleft_no_rankings[] = 
"SELECT DISTINCT map "...
	"FROM `mapzones` "...
	"WHERE type = 0 AND track = %d AND map "...
	"NOT IN "...
		"(SELECT DISTINCT map "...
		"FROM `playertimes` "...
		"WHERE auth = %d AND style = %d AND track = %d) "...
		"ORDER BY map;";

char mysql_showmaps_details[] = 
"SELECT u.name, "...
	"p.time, "...
	"p.jumps, "...
	"p.style, "...
	"u.auth, "...
	"p.date, "...
	"p.map, "...
	"p.strafes, "...
	"p.sync, "...
	"p.points "...
	"FROM `playertimes` p "...
	"JOIN `users` u "...
	"ON p.auth = u.auth "...
	"WHERE p.id = '%s' "...
	"LIMIT 1;";

char mysql_top_playtime[] = 
"(SELECT auth, name, playtime, -1 as ownrank FROM `users` WHERE playtime > 0 ORDER BY playtime DESC LIMIT 100) " ...
		"UNION " ...
		"(SELECT -1, '', u2.playtime, COUNT(*) as ownrank FROM `users` u1 JOIN (SELECT playtime FROM `users` WHERE auth = %d) u2 WHERE u1.playtime >= u2.playtime);";

char mysql_show_stats_with_rankings[] = 
"SELECT a.clears, b.maps, c.wrs, d.name, d.ip, d.lastlogin, f.clears, g.maps, h.wrs, d.points, e.rank, d.playtime, i.styleplaytime FROM "...
	"(SELECT COUNT(*) clears FROM (SELECT map FROM `playertimes` WHERE auth = %d AND track = 0 AND style = %d GROUP BY map) s) a "...
	"JOIN (SELECT COUNT(*) maps FROM (SELECT map FROM `mapzones` WHERE track = 0 AND type = 0 GROUP BY map) s) b "...
	"JOIN (SELECT COUNT(*) wrs FROM `wrs` WHERE auth = %d AND track = 0 AND style = %d) c "...
	"JOIN (SELECT name, ip, lastlogin, FORMAT(points, 2) points, playtime FROM `users` WHERE auth = %d) d "...
	"JOIN (SELECT COUNT(*) as 'rank' FROM `users` as u1 JOIN (SELECT points FROM `users` WHERE auth = %d) u2 WHERE u1.points >= u2.points) e "...
	"JOIN (SELECT COUNT(*) clears FROM (SELECT map FROM `playertimes` WHERE auth = %d AND track > 0 AND style = %d GROUP BY map) s) f "...
	"JOIN (SELECT COUNT(*) maps FROM (SELECT map FROM `mapzones` WHERE track > 0 AND type = 0 GROUP BY map) s) g "...
	"JOIN (SELECT COUNT(*) wrs FROM `wrs` WHERE auth = %d AND track > 0 AND style = %d) h "...
	"JOIN (SELECT SUM(playtime) as styleplaytime FROM `styleplaytime` WHERE auth = %d AND style = %d) i "...
		"LIMIT 1;";

char mysql_show_stats_no_rankings[] = 
"SELECT a.clears, b.maps, c.wrs, d.name, d.ip, d.lastlogin, e.clears, f.maps, g.wrs, d.playtime, i.styleplaytime FROM "...
	"(SELECT COUNT(*) clears FROM (SELECT map FROM `playertimes` WHERE auth = %d AND track = 0 AND style = %d GROUP BY map) s) a "...
	"JOIN (SELECT COUNT(*) maps FROM (SELECT map FROM `mapzones` WHERE track = 0 AND type = 0 GROUP BY map) s) b "...
	"JOIN (SELECT COUNT(*) wrs FROM `wrs` WHERE auth = %d AND track = 0 AND style = %d) c "...
	"JOIN (SELECT name, ip, lastlogin, playtime FROM `users` WHERE auth = %d) d "...
	"JOIN (SELECT COUNT(*) clears FROM (SELECT map FROM `playertimes` WHERE auth = %d AND track > 0 AND style = %d GROUP BY map) s) e "...
	"JOIN (SELECT COUNT(*) maps FROM (SELECT map FROM `mapzones` WHERE track > 0 AND type = 0 GROUP BY map) s) f "...
	"JOIN (SELECT COUNT(*) wrs FROM `wrs` WHERE auth = %d AND track > 0 AND style = %d) g "...
	"JOIN (SELECT SUM(playtime) as styleplaytime FROM `styleplaytime` WHERE auth = %d AND style = %d) i "...
		"LIMIT 1;";