/*
    Table querys.
*/



// ======[ TABLE CREATE ]======

char mysql_table_create[] = 
"CREATE TABLE IF NOT EXISTS `styleplaytime` "...
    "(`auth` INT NOT NULL, "...
    "`style` INT NOT NULL, "...
    "`playtime` FLOAT NOT NULL, "...
    "PRIMARY KEY (`auth`, `style`));";



// ======[ TABLE INSERT ]======





// ======[ TABLE QUERY ]======

char mysql_query_style_playtime[] = 
"SELECT style, playtime "...
    "FROM `styleplaytime` "...
    "WHERE auth = %d;";

char mysql_update_regular_playtime[] = 
"UPDATE `users` "...
    "SET playtime = playtime + %f "...
    "WHERE auth = %d;";

char mysql_update_style_playtime[] = 
"UPDATE `styleplaytime` "...
    "SET playtime = playtime + %f "...
    "WHERE auth = %d AND style = %d;";

char mysql_insert_style_playtime[] = 
"INSERT INTO `styleplaytime` "...
    "(`auth`, `style`, `playtime`) VALUES "...
    "(%d, %d, %f);";

char mysql_show_mapsdone[] = 
"SELECT a.map, a.time, a.jumps, a.id, COUNT(b.map) + 1 as 'rank', a.points "...
    "FROM `playertimes` a "...
    "LEFT JOIN `playertimes` b "...
    "ON a.time > b.time AND a.map = b.map AND a.style = b.style AND a.track = b.track "...
    "WHERE a.auth = %d AND a.style = %d AND a.track = %d "...
    "GROUP BY a.map, a.time, a.jumps, a.id, a.points "...
    "ORDER BY a.%s;";