/*
	SQL query templates.
*/



// ======[ TABLE CREATE ]=======

char mysql_create_table_chat[] = 
"CREATE TABLE IF NOT EXISTS `chat` "...
	"(`auth` INT NOT NULL, "...
	"`name` INT NOT NULL DEFAULT 0, "...
	"`ccname` VARCHAR(128) COLLATE 'utf8mb4_unicode_ci', "...
	"`message` INT NOT NULL DEFAULT 0, "...
	"`ccmessage` VARCHAR(16) COLLATE 'utf8mb4_unicode_ci', "...
	"`ccaccess` INT NOT NULL DEFAULT 0, "...
	"PRIMARY KEY (`auth`), "...
	"CONSTRAINT `ch_auth` FOREIGN KEY (`auth`) REFERENCES `users` (`auth`) "...
	"ON UPDATE CASCADE ON DELETE CASCADE) "...
	"ENGINE=INNODB;";


// ======[ TABLE QUERY ]======

char mysql_load_chat_settings[] = 
"SELECT name, "...
	"ccname, "...
	"message, "...
	"ccmessage, "...
	"ccaccess "...
	"FROM `chat` "...
	"WHERE auth = %d;";



// ======[ TABLE UPDATE ]======

char mysql_update_chat_settings[] = 
"REPLACE INTO `chat` "...
	"(auth, name, ccname, message, ccmessage) VALUES "...
	"(%d, %d, '%s', %d, '%s');";

char mysql_add_cc_access[] = 
"REPLACE INTO `chat` "...
	"(auth, ccaccess) VALUES "...
	"(%d, 1);";

char mysql_delete_cc_access[] = 
"UPDATE `chat` "...
	"SET ccaccess = 0 "...
	"WHERE auth = %d;";