/*
 * shavit's Timer - .inc file
 * by: shavit
 *
 * This file is part of shavit's Timer.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *
*/

#if defined _shavit_included
	#endinput
#endif
#define _shavit_included

// Note: Including shavit.inc will also include all the following files!
//       If you don't wanna include such a lot of stuff, you can just include shavit/core.inc
//       and other files your plugin needs.

#include <shavit/chat>
#include <shavit/checkpoints>
#include <shavit/core>
#include <shavit/hud>
#include <shavit/mapchooser>
#include <shavit/misc>
#include <shavit/rankings>
#include <shavit/replay-playback>
#include <shavit/replay-recorder>
#include <shavit/sounds>
#include <shavit/stage>
#include <shavit/stats>
#include <shavit/timelimit>
#include <shavit/wr>
#include <shavit/zones>

#include <shavit/colors>
#include <shavit/map_folder_stocks>
#include <shavit/replay-shared>
#include <shavit/surftimer>